name = "FasterShortestPaths"
uuid = "952f73ac-809b-4467-8cda-03990de1fa90"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataStructures = "0.19.1"
Graphs = "1.13.1"
Random = "1.11.0"
SimpleWeightedGraphs = "1.5.0"
SparseArrays = "1.11.0"
